package com.allaboutjava.basicconcepts.files;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class WriteFileUsingBufferedWriter {

  public static void main(String[] args) throws IOException {
    String content = "Hi there!\nThis is a sample file generated by java code using BufferedWriter";
    BufferedWriter writer = new BufferedWriter(
        new FileWriter("/Users/sadiqhus/mygit/personal/allaboutjava/sample_files/test1.txt"));
    writer.write(content);
    writer.close();
    System.out.println("Writing completed!");
  }

}
